language: csharp

mono: none
dotnet: 3.1.101

before_install:
    - sudo apt-get install nuget

install:
    - nuget restore Example/Example.sln

script:
    - dotnet test Example/Example.sln